### ISSUE TITLE
tests: intermittent test failure

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/wasapi-downloader#103]
(rerunning usually fixes it ... test order dependent???)

looks like this:

```
edu.stanford.dlss.was.TestWasapiDownloader_PowerMock > main_callsExecutFromCmdLine FAILED
    org.mockito.exceptions.misusing.InvalidUseOfMatchersException: 
    Invalid use of argument matchers!
    2 matchers expected, 4 recorded:
    -> at edu.stanford.dlss.was.TestWasapiDownloader_PowerMock.checksumValidate_missingChecksumPrintsErrorAndReturnsFalse(TestWasapiDownloader_PowerMock.java:215)
    -> at edu.stanford.dlss.was.TestWasapiDownloader_PowerMock.checksumValidate_unsupportedAlgorithmReturnsFalse(TestWasapiDownloader_PowerMock.java:231)
    -> at edu.stanford.dlss.was.TestWasapiDownloader_PowerMock.main_callsExecutFromCmdLine(TestWasapiDownloader_PowerMock.java:36)
    -> at edu.stanford.dlss.was.TestWasapiDownloader_PowerMock.main_callsExecutFromCmdLine(TestWasapiDownloader_PowerMock.java:36)

    This exception may occur if matchers are combined with raw values:
        //incorrect:
        someMethod(anyObject(), "raw String");
    When using matchers, all arguments have to be provided by matchers.
    For example:
        //correct:
        someMethod(anyObject(), eq("String by matcher"));

    For more info see javadoc for Matchers class.
        at edu.stanford.dlss.was.TestWasapiDownloader_PowerMock.main_callsExecutFromCmdLine(TestWasapiDownloader_PowerMock.java:36)

```

**Comment by ndushay** [comment]
I believe this is now fixed.
